# Generated by Django 5.2.8 on 2026-09-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedstudent',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deletedstudent',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deletedstudent',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deletedstudent',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deletedstudent',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deletedstudent',
            name='time_slot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='days',
            field=models.CharField(default='Dushanba, Chorshanba, Juma', max_length=100),
        ),
    ]
