# Generated by Django 5.2.8 on 2026-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deletedstudent_age_deletedstudent_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_1', models.CharField(max_length=20)),
                ('phone_2', models.CharField(blank=True, default='', max_length=20)),
                ('subject', models.CharField(help_text='Qaysi fan / kurs', max_length=100)),
                ('preferred_time', models.CharField(blank=True, default='', help_text='Qaysi soatga kelgan', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
