# Generated by Django 5.2.8 on 2026-09-22 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_temporarystudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_rate',
            field=models.IntegerField(default=0, help_text="Oylik to'lov summasi"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Keldi (+)'), ('absent', 'Kelmadi (-)')], max_length=10),
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Yil va Oy. Masalan: 2026-09', max_length=7)),
                ('amount_paid', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'month')},
            },
        ),
    ]
