# Generated by Django 5.2.8 on 2026-09-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_payment_rate_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_custom_credentials',
            field=models.BooleanField(default=False, help_text="Admin o'zi alohida login-parol yaratganmi?"),
        ),
    ]
