# Generated by Django 5.2.8 on 2026-09-25 10:20

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_has_custom_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedstudent',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, validators=[core.validators.validate_latin_only]),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, validators=[core.validators.validate_latin_only]),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, validators=[core.validators.validate_latin_only]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, validators=[core.validators.validate_latin_only]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, validators=[core.validators.validate_latin_only]),
        ),
        migrations.AlterField(
            model_name='temporarystudent',
            name='first_name',
            field=models.CharField(max_length=100, validators=[core.validators.validate_latin_only]),
        ),
        migrations.AlterField(
            model_name='temporarystudent',
            name='last_name',
            field=models.CharField(max_length=100, validators=[core.validators.validate_latin_only]),
        ),
        migrations.AlterField(
            model_name='temporarystudent',
            name='notes',
            field=models.TextField(blank=True, default='', validators=[core.validators.validate_latin_only]),
        ),
        migrations.AlterField(
            model_name='temporarystudent',
            name='preferred_time',
            field=models.CharField(blank=True, default='', help_text='Qaysi soatga kelgan', max_length=100, validators=[core.validators.validate_latin_only]),
        ),
        migrations.AlterField(
            model_name='temporarystudent',
            name='subject',
            field=models.CharField(help_text='Qaysi fan / kurs', max_length=100, validators=[core.validators.validate_latin_only]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='days',
            field=models.CharField(default='Dushanba, Chorshanba, Juma', max_length=100, validators=[core.validators.validate_latin_only]),
        ),
    ]
