# Generated by Django 6.1.1 on 2026-09-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_deletedstudent_reason_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text="O'quvchi rasmi (ixtiyoriy)", null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='can_edit_students',
            field=models.BooleanField(default=False, help_text="O'qituvchiga o'quvchilarni tahrirlash ruxsati"),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
