# Generated by Django 5.2.8 on 2026-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='amount_paid',
            field=models.CharField(default='', help_text="To'lov summasi yoki izoh", max_length=100),
        ),
    ]
