# Generated by Django 5.2.8 on 2026-09-30 21:03

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_monthlypayment_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Fan nomi', max_length=100, validators=[core.validators.validate_latin_only]),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='notes',
            field=models.CharField(blank=True, default='', help_text="Izoh yoki to'lov turi", max_length=255),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='payment_date',
            field=models.DateField(blank=True, help_text="To'lov qilingan sana", null=True),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='status',
            field=models.CharField(choices=[('paid', "To'langan"), ('partial', "Qisman to'langan"), ('unpaid', "To'lanmagan")], default='paid', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
