# Generated by Django 5.2.8 on 2026-09-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_group_subject_monthlypayment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_local',
            field=models.BooleanField(default=False, verbose_name="Mahalladan keladigan o'quvchi"),
        ),
    ]
