# Generated by Django 5.2.8 on 2026-10-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_student_is_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedstudent',
            name='student_id',
            field=models.IntegerField(blank=True, help_text='Asosiy Student ID si', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='left_date',
            field=models.DateField(blank=True, help_text="Guruhdan o'chirilgan/chiqqan sana", null=True),
        ),
    ]
